### ISSUE TITLE
[Suggestion] Add fishing bounties to fishing loot pool

### ISSUE THREAD

**Issue by JohnVKS** [ejektaflex/Bountiful-Fabric#2]
## Add bount drop from fishing

Add some rare bounties from fishing, I think it can be nice if  the player is not really into finding villages

Edit: Maybe even make some of them exclusive of fishing

**Comment by ejektaflex** [comment]
I've added a bounty that relates to fishing up enchanted books. If any new ideas crop up, feel free to post them here:
https://github.com/ejektaflex/Bountiful/discussions
