### ISSUE TITLE
[Bug] Any Item requirement doesnt check for amount

### ISSUE THREAD

**Issue by Secretname2009** [ejektaflex/Bountiful-Fabric#20]
I stumbled upon this bug that when a bounty requires an amount of "Any Banner", it doesnt check for how many or if you have any at all.
That means i can claim any bounty requiring Any Banner without cost.
This also appears toi apply to all "Any XXX" Requirements.
This is present in Bountiful Fabric 2.0.2

**Comment by ejektaflex** [comment]
This has been fixed in the upcoming version for 1.19.4
