### ISSUE TITLE
Numismatic Overhaul Compatibility

### ISSUE THREAD

**Issue by cntrik** [ejektaflex/Bountiful-Fabric#21]
FEATURE REQUEST:
A recently made mod featuring a currency and trading overhaul [link](https://www.curseforge.com/minecraft/mc-mods/numismatic-overhaul), bounties providing rewards in the currency would be amazing.

**Comment by ejektaflex** [comment]
Once I reimplement command rewards, you should be able to create an entry that rewards you with currency!

**Comment by ejektaflex** [comment]
Actually, I've already done it.

You can find information on customizing bounties [here](https://kambrik.ejekta.io/mods/bountiful/wiki/CustomizingBounties.html).

Thanks!
