### ISSUE TITLE
Will there be a 1.18.2 update?

### ISSUE THREAD

**Issue by bluejt** [ejektaflex/Bountiful-Fabric#28]
Will there be a 1.18.2 update? I am looking forward to it

**Comment by ejektaflex** [comment]
Yep! I'm really busy right now - in the process of moving and marriage. Thanks for the question!

**Comment by Laifsyn** [comment]
Congratz on your wedding

**Comment by Razatop** [comment]
I'm simply guessing here, but. Don't think were gonna get a 1.18.2 version are we? Think I've read a few comments where you state it wont happen. Which is a shame for those who don't want to move forward to 1.19 based on mojangs actions.

**Comment by ejektaflex** [comment]
Sorry - I've since skipped 1.18.2 and ported to 1.19. There will not be a 1.18.2 update, as I didn't have time for a port to that version. The Fabric version will continue to receive updates to the newest versions of Minecraft as long as I have time, but that may not be every version!
