### ISSUE TITLE
Fabric 0.13.3-1.18.2 crashes when trying to load bountiful 2.0.1

### ISSUE THREAD

**Issue by Mensh123** [ejektaflex/Bountiful-Fabric#29]
lastest.log: https://pastebin.com/xtDfU3HQ
crash report: https://pastebin.com/SsKV8ggf

**Comment by Goddessa39** [comment]
I have played with this mod previously and loved it but 1.18.2 just crashes with it.

**Comment by ejektaflex** [comment]
That's because it doesn't yet work with 1.18.2. See #28 :)
