### ISSUE TITLE
Fails to compile due to jcenter's and bintray's shutdown

### ISSUE THREAD

**Issue by ghost** [ejektaflex/Bountiful-Fabric#3]
Pretty self-explanatory. absolutely ridiculous that jfrog did this with almost no warning.

**Comment by ejektaflex** [comment]
Ah - right. You should be able to switch the Kotlin Bintray to something else when compiling. I believe it's used for KotlinX Serialization, but could be wrong. This project is pretty much in a working state, but only includes item and mob bounties.

**Comment by ejektaflex** [comment]
It should be all good now - though there will be some bugs as of the current commit. This was a very quick port to 1.17 and still needs some work (notably the Bounty Board GUI is broken, but that seems to be it). I'm still doing some work on the dependent library, Kambrik, before I make an official release there. Once that's done, I'll be back to finishing Bountiful and releasing it for Fabric!

**Comment by ghost** [comment]
Thanks for the fix, best of luck with this mod
