### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Gilithrimm** [ejektaflex/Bountiful-Fabric#30]
crashlog: [crashlog.txt](https://github.com/ejektaflex/Bountiful-Fabric/files/8630829/crashlog.txt)
after downloading version 2.0.2 from curseforge, my launcher said it's version 2.0.1, idk why
also logs if you need them [latest.log](https://github.com/ejektaflex/Bountiful-Fabric/files/8630842/latest.log)

have a nice day/sleep!

**Comment by ejektaflex** [comment]
You're running the game on 1.18.2, and Bountiful-Fabric is for 1.18.1. I won't be doing a 1.18.2 port, but rather skipping right to 1.19. Sorry!
