### ISSUE TITLE
Not working on 1.19

### ISSUE THREAD

**Issue by Surpos0** [ejektaflex/Bountiful-Fabric#31]
it's not working on 1.19 now you can name it officially as a reported bug. Game just tell you that you have wrong version.

ps: im doing that cuz of your comment

**Comment by ejektaflex** [comment]
Cool, thank you! Although unfortunately while it not working on 1.19 is a shame, I don't have time to backport it to 1.19 in the same way that I don't have time for a backport to 1.18.2. As such, only the latest version (currently 1.19.2) will be supported right now.
