### ISSUE TITLE
Bounty boards not allowing submission when completed

### ISSUE THREAD

**Issue by carefulpear21** [ejektaflex/Bountiful-Fabric#35]
I have taken 2 bounties from 2 different boards and I cannot submit these at all by following the instructions on the mod

**Comment by ejektaflex** [comment]
What did you attempt to to? If you could be more specific about what you tried, that would be great. Also, supplying version numbers for Bountiful, for Kambrik and for Minecraft are needed because things change from version to version.

**Comment by carefulpear21** [comment]
I selected a bounty to complete, upon fulfilling its requirements I then take it back to the bounty board and follow the mods mechanics - 

"Bounty boards can be found throughout the world in villages, and they'll generate bounties inside of them. These bounties often ask for you to bring back an item, or kill some mobs in return for whatever rewards they're offering. **If you can complete the bounty, you just have to bring it back to the bounty board and right click the board to redeem your rewards!"**

When I do this it does not do anything, I am still left with the bounty, I do not get the reward and the bounty is in my inventory unless I throw it away. 

Mod version Minecraft 1.19
**BountifulFabric-4.0.0.jar**

I am using the mod in **Better MC [FABRIC] 1.19.2 V11** (Most current update)

I hope this info helps

**Comment by carefulpear21** [comment]
I have fixed this now for me. thank you
