### ISSUE TITLE
Not Working on 1.19.3

### ISSUE THREAD

**Issue by SnowJay2005** [ejektaflex/Bountiful-Fabric#39]
I'm sure you're probably already working on an update, but in case you didn't know that 1.19.3 broke the mod, thought I'd let you know

**Comment by ejektaflex** [comment]
Yeah, Minecraft updates usually break mods. Note that it's not marked as compatible on CurseForge :^)

But I listed the mod JSON dependency range slightly incorrectly, so it still attempts to load. I'll be releasing a 1.19.3 version when I can!

**Comment by ejektaflex** [comment]
It's been updated and a new version has been released! Make sure to update Kambrik as well!
