### ISSUE TITLE
1,17 multiple bounty boards?

### ISSUE THREAD

**Issue by thijsi123** [ejektaflex/Bountiful-Fabric#6]
I just started the game with the mod installed of course.
I teleported to multiple villages and all of them had 3 bounty boards.
I don't know if this is supposed to be like this but I thought to mention it at least.

**Comment by thijsi123** [comment]
Oh, never mind I see it now.

**Comment by ejektaflex** [comment]
Three is quite a lot. It should be more like 1-2 on average. Let me know if it's unusually high, I can tone down the frequency a bit.

**Comment by thijsi123** [comment]
Oh, so it is. Well I did some further testing and came across one village with 5 boards. the previous village in the same new world had 3 boards btw.
![image](https://user-images.githubusercontent.com/64159148/131375763-8f07d098-f0b6-4177-bea8-86d6319422cc.png)

**Comment by ejektaflex** [comment]
Wew, okay. The current generation frequency is 4, I will reduce it to 2. 

Mojang may have tweaked their village jigsaw piece weights (these determine how often different types of structures show up in villages), making mine relatively higher. Thank you.

**Comment by thijsi123** [comment]
It's nothing I'm grateful that I could help.
